# Generated by Django 3.2.23 on 2024-06-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20240622_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_index', models.IntegerField()),
                ('share_value', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.filehandle')),
            ],
        ),
    ]
